name: Publish Cargo Crate

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Publish Crate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y meson ninja-build

      - name: Clone and build Filerix
        run: |
          git clone https://github.com/filesverse/filerix.git
          cd filerix
          meson setup build
          ninja -C build
          sudo ninja -C build install
          cd .. && rm filerix -rf

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build the crate
        run: cargo build --release

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
